#!/bin/bash

gcc -o keygen keygen.c otp_helpers.c -std=c99
gcc -o otp_enc otp_enc.c otp_helpers.c 
gcc -o otp_enc_d otp_enc_d.c otp_helpers.c 
gcc -o otp_dec otp_dec.c otp_helpers.c 
gcc -o otp_dec_d otp_dec_d.c otp_helpers.c 
